### ISSUE TITLE
Crash durante instalación

### ISSUE THREAD

**Issue by pabalarc** [bitasuperactive/BlockTheSpot-C-Sharp#2]
Hola. Te felicito por tu trabajo. Venía usando sin problemas tu instalador, pero últimamente me dio errores. Creería que justo después de la instalación de spotify v.1.1.4, se crashea. Ésto me pasó en W10 y en W7, ambos en versión 64bits. Saludos desde Argentina.
<img width="260" alt="crash" src="https://user-images.githubusercontent.com/4376100/108347735-a2dcbe80-71bf-11eb-9d95-e652fa946a04.png">

**Comment by bitasuperactive** [comment]
Ese error hace referencia a un problema con la descarga de _netutils.dll_, desde el enlace `https://raw.githubusercontent.com/master131/BlockTheSpot/master/netutils.dll`, excepción que ya estaba controlada en la versión _1.3-beta_ de 02-2020, pero que por algún motivo no subí.
Gracias por la aportación @pabalarc.
